[2023-04-07T12:23:21.793-0300] {processor.py:153} INFO - Started process (PID=1387) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:23:21.794-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:23:21.794-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:23:21.794-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:23:21.797-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:23:21.796-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:23:21.797-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:23:21.813-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.022 seconds
[2023-04-07T12:24:07.032-0300] {processor.py:153} INFO - Started process (PID=1444) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:24:07.036-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:24:07.036-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:24:07.036-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:24:07.038-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:24:07.038-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:24:07.038-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:24:07.053-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.024 seconds
[2023-04-07T12:24:46.056-0300] {processor.py:153} INFO - Started process (PID=1486) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:24:46.061-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:24:46.061-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:24:46.061-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:24:46.063-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:24:46.063-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:24:46.064-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:24:46.079-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.025 seconds
[2023-04-07T12:25:28.502-0300] {processor.py:153} INFO - Started process (PID=1528) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:25:28.504-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:25:28.505-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:25:28.504-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:25:28.508-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:25:28.507-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:25:28.508-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:25:28.524-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.026 seconds
[2023-04-07T12:26:05.683-0300] {processor.py:153} INFO - Started process (PID=1566) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:26:05.688-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:26:05.689-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:26:05.688-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:26:05.691-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:26:05.690-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:26:05.691-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:26:05.706-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.025 seconds
[2023-04-07T12:26:43.028-0300] {processor.py:153} INFO - Started process (PID=1604) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:26:43.032-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:26:43.033-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:26:43.033-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:26:43.034-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:26:43.034-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:26:43.035-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:26:43.049-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.024 seconds
[2023-04-07T12:27:20.271-0300] {processor.py:153} INFO - Started process (PID=1641) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:27:20.273-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:27:20.273-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:27:20.273-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:27:20.275-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:27:20.274-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:27:20.275-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:27:20.288-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.020 seconds
[2023-04-07T12:28:00.327-0300] {processor.py:153} INFO - Started process (PID=1684) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:28:00.331-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:28:00.332-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:28:00.332-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:28:00.334-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:28:00.333-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:28:00.334-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:28:00.349-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.024 seconds
[2023-04-07T12:28:37.991-0300] {processor.py:153} INFO - Started process (PID=1723) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:28:37.994-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:28:37.995-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:28:37.994-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:28:37.998-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:28:37.997-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:28:37.999-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:28:38.029-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.043 seconds
[2023-04-07T12:29:19.139-0300] {processor.py:153} INFO - Started process (PID=1762) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:29:19.144-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:29:19.145-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:29:19.145-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:29:19.149-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:29:19.148-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:29:19.149-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:29:19.176-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.042 seconds
[2023-04-07T12:29:57.185-0300] {processor.py:153} INFO - Started process (PID=1802) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:29:57.187-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:29:57.188-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:29:57.188-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:29:57.192-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:29:57.191-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:29:57.193-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:29:57.217-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.035 seconds
[2023-04-07T12:30:34.947-0300] {processor.py:153} INFO - Started process (PID=1839) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:30:34.950-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:30:34.951-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:30:34.951-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:30:34.954-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:30:34.953-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:30:34.955-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:30:34.975-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.033 seconds
[2023-04-07T12:31:24.279-0300] {processor.py:153} INFO - Started process (PID=1883) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:31:24.281-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:31:24.282-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:31:24.282-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:31:24.284-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:31:24.284-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:31:24.285-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:31:24.301-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.024 seconds
[2023-04-07T12:32:04.284-0300] {processor.py:153} INFO - Started process (PID=1924) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:32:04.285-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:32:04.286-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:32:04.286-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:32:04.287-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:32:04.287-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:32:04.288-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:32:04.301-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.019 seconds
[2023-04-07T12:32:42.175-0300] {processor.py:153} INFO - Started process (PID=1960) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:32:42.180-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:32:42.181-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:32:42.181-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:32:42.185-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:32:42.184-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:32:42.187-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:32:42.214-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.045 seconds
[2023-04-07T12:33:21.475-0300] {processor.py:153} INFO - Started process (PID=2000) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:33:21.477-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:33:21.478-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:33:21.478-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:33:21.482-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:33:21.481-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:33:21.484-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:33:21.508-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.036 seconds
[2023-04-07T12:34:02.979-0300] {processor.py:153} INFO - Started process (PID=2039) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:34:02.980-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:34:02.981-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:34:02.981-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:34:02.983-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:34:02.982-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:34:02.983-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:34:02.997-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.021 seconds
[2023-04-07T12:34:42.938-0300] {processor.py:153} INFO - Started process (PID=2079) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:34:42.946-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:34:42.947-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:34:42.947-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:34:42.949-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:34:42.949-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:34:42.950-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:34:42.965-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.029 seconds
[2023-04-07T12:35:19.994-0300] {processor.py:153} INFO - Started process (PID=2117) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:35:19.999-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:35:20.000-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:35:19.999-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:35:20.002-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:35:20.001-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:35:20.002-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:35:20.017-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.025 seconds
[2023-04-07T12:35:58.312-0300] {processor.py:153} INFO - Started process (PID=2154) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:35:58.313-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:35:58.314-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:35:58.313-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:35:58.316-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:35:58.315-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:35:58.316-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:35:58.332-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.022 seconds
[2023-04-07T12:36:34.030-0300] {processor.py:153} INFO - Started process (PID=2192) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:36:34.035-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:36:34.035-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:36:34.035-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:36:34.037-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:36:34.037-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:36:34.037-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:36:34.052-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.025 seconds
[2023-04-07T12:37:14.377-0300] {processor.py:153} INFO - Started process (PID=2235) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:37:14.379-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:37:14.379-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:37:14.379-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:37:14.381-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:37:14.380-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:37:14.381-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:37:14.396-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.021 seconds
[2023-04-07T12:37:58.195-0300] {processor.py:153} INFO - Started process (PID=2279) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:37:58.200-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:37:58.200-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:37:58.200-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:37:58.202-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:37:58.202-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:37:58.202-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:37:58.217-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.024 seconds
[2023-04-07T12:38:31.963-0300] {processor.py:153} INFO - Started process (PID=2314) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:38:31.967-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:38:31.968-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:38:31.968-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:38:31.970-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:38:31.969-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:38:31.970-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:38:31.985-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.024 seconds
[2023-04-07T12:39:06.743-0300] {processor.py:153} INFO - Started process (PID=2350) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:39:06.747-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:39:06.748-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:39:06.748-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:39:06.750-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:39:06.749-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:39:06.750-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:39:06.764-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.023 seconds
[2023-04-07T12:39:43.700-0300] {processor.py:153} INFO - Started process (PID=2386) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:39:43.705-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:39:43.705-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:39:43.705-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:39:43.707-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:39:43.707-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:39:43.708-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:39:43.723-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.025 seconds
[2023-04-07T12:40:21.783-0300] {processor.py:153} INFO - Started process (PID=2424) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:40:21.788-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:40:21.789-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:40:21.789-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:40:21.791-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:40:21.791-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:40:21.792-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:40:21.807-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.026 seconds
[2023-04-07T12:41:04.755-0300] {processor.py:153} INFO - Started process (PID=2465) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:41:04.756-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:41:04.757-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:41:04.757-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:41:04.759-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:41:04.758-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:41:04.759-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:41:04.772-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.019 seconds
[2023-04-07T12:41:43.591-0300] {processor.py:153} INFO - Started process (PID=2503) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:41:43.596-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:41:43.597-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:41:43.597-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:41:43.599-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:41:43.599-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:41:43.599-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:41:43.614-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.026 seconds
[2023-04-07T12:42:26.572-0300] {processor.py:153} INFO - Started process (PID=2544) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:42:26.578-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:42:26.579-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:42:26.579-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:42:26.581-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:42:26.580-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:42:26.581-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:42:26.595-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.025 seconds
[2023-04-07T12:43:05.688-0300] {processor.py:153} INFO - Started process (PID=2584) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:43:05.693-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:43:05.694-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:43:05.693-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:43:05.695-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:43:05.695-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:43:05.695-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:43:05.710-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.024 seconds
[2023-04-07T12:43:51.220-0300] {processor.py:153} INFO - Started process (PID=2630) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:43:51.221-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:43:51.222-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:43:51.222-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:43:51.223-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:43:51.223-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:43:51.224-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:43:51.238-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.020 seconds
[2023-04-07T12:44:28.972-0300] {processor.py:153} INFO - Started process (PID=2667) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:44:28.978-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:44:28.978-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:44:28.978-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:44:28.980-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:44:28.979-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:44:28.980-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:44:28.994-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.024 seconds
[2023-04-07T12:45:11.135-0300] {processor.py:153} INFO - Started process (PID=2708) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:45:11.140-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:45:11.141-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:45:11.141-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:45:11.143-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:45:11.143-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:45:11.143-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:45:11.158-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.027 seconds
[2023-04-07T12:45:53.785-0300] {processor.py:153} INFO - Started process (PID=2749) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:45:53.786-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:45:53.787-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:45:53.787-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:45:53.788-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:45:53.788-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:45:53.789-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:45:53.803-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.021 seconds
[2023-04-07T12:47:59.270-0300] {processor.py:153} INFO - Started process (PID=2800) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:47:59.272-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:47:59.273-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:47:59.273-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:47:59.277-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:47:59.276-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:47:59.278-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:47:59.303-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.038 seconds
[2023-04-07T12:48:43.602-0300] {processor.py:153} INFO - Started process (PID=2842) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:48:43.604-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:48:43.606-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:48:43.605-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:48:43.609-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:48:43.608-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:48:43.610-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:48:43.635-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.036 seconds
[2023-04-07T12:49:28.570-0300] {processor.py:153} INFO - Started process (PID=2883) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:49:28.575-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:49:28.576-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:49:28.576-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:49:28.580-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:49:28.579-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:49:28.581-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:49:28.607-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.041 seconds
[2023-04-07T12:50:21.282-0300] {processor.py:153} INFO - Started process (PID=2928) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:50:21.284-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:50:21.285-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:50:21.285-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:50:21.289-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:50:21.288-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:50:21.290-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:50:21.319-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.042 seconds
[2023-04-07T12:51:01.992-0300] {processor.py:153} INFO - Started process (PID=2962) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:51:01.994-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:51:01.996-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:51:01.995-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:51:02.000-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:51:01.998-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:51:02.000-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:51:02.025-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.038 seconds
[2023-04-07T12:51:40.326-0300] {processor.py:153} INFO - Started process (PID=2995) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:51:40.328-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:51:40.329-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:51:40.329-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:51:40.335-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:51:40.333-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:51:40.335-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:51:40.364-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.044 seconds
[2023-04-07T12:52:21.421-0300] {processor.py:153} INFO - Started process (PID=3029) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:52:21.423-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:52:21.425-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:52:21.424-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:52:21.429-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:52:21.428-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:52:21.430-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:52:21.460-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.044 seconds
[2023-04-07T12:53:00.032-0300] {processor.py:153} INFO - Started process (PID=3063) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:53:00.038-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:53:00.039-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:53:00.039-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:53:00.043-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:53:00.042-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:53:00.043-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:53:00.069-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.040 seconds
[2023-04-07T12:53:36.655-0300] {processor.py:153} INFO - Started process (PID=3096) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:53:36.657-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:53:36.658-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:53:36.658-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:53:36.663-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:53:36.662-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:53:36.664-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:53:36.689-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.039 seconds
[2023-04-07T12:54:18.316-0300] {processor.py:153} INFO - Started process (PID=3138) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:54:18.317-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:54:18.317-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:54:18.317-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:54:18.319-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:54:18.319-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:54:18.319-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:54:18.335-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.021 seconds
[2023-04-07T12:54:55.513-0300] {processor.py:153} INFO - Started process (PID=3175) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:54:55.515-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:54:55.515-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:54:55.515-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:54:55.517-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:54:55.516-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:54:55.517-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:54:55.532-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.021 seconds
[2023-04-07T12:55:46.822-0300] {processor.py:153} INFO - Started process (PID=3222) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:55:46.827-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:55:46.829-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:55:46.829-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:55:46.833-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:55:46.832-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:55:46.833-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:55:46.866-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.048 seconds
[2023-04-07T12:56:26.463-0300] {processor.py:153} INFO - Started process (PID=3257) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:56:26.465-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:56:26.466-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:56:26.465-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:56:26.469-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:56:26.468-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:56:26.469-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:56:26.488-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.029 seconds
[2023-04-07T12:57:19.035-0300] {processor.py:153} INFO - Started process (PID=3307) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:57:19.036-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:57:19.037-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:57:19.036-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:57:19.039-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:57:19.038-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:57:19.039-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:57:19.054-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.022 seconds
[2023-04-07T12:58:02.888-0300] {processor.py:153} INFO - Started process (PID=3351) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:58:02.889-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:58:02.890-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:58:02.890-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:58:02.893-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:58:02.892-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:58:02.893-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:58:02.914-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.029 seconds
[2023-04-07T12:58:43.392-0300] {processor.py:153} INFO - Started process (PID=3392) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:58:43.393-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:58:43.394-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:58:43.394-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:58:43.396-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:58:43.396-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:58:43.397-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:58:43.414-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.024 seconds
[2023-04-07T12:59:21.458-0300] {processor.py:153} INFO - Started process (PID=3431) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:59:21.459-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T12:59:21.460-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:59:21.460-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:59:21.462-0300] {logging_mixin.py:137} INFO - [2023-04-07T12:59:21.461-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T12:59:21.462-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T12:59:21.475-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.019 seconds
[2023-04-07T13:00:03.704-0300] {processor.py:153} INFO - Started process (PID=3470) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:00:03.706-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:00:03.707-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:00:03.707-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:00:03.711-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:00:03.710-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:00:03.711-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:00:03.737-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.039 seconds
[2023-04-07T13:00:42.827-0300] {processor.py:153} INFO - Started process (PID=3508) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:00:42.828-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:00:42.829-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:00:42.829-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:00:42.830-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:00:42.830-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:00:42.831-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:00:42.846-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.021 seconds
[2023-04-07T13:01:22.261-0300] {processor.py:153} INFO - Started process (PID=3556) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:01:22.266-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:01:22.268-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:01:22.267-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:01:22.272-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:01:22.271-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:01:22.273-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:01:22.301-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.046 seconds
[2023-04-07T13:02:03.362-0300] {processor.py:153} INFO - Started process (PID=3597) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:02:03.364-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:02:03.366-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:02:03.365-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:02:03.371-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:02:03.370-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:02:03.372-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:02:03.400-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.043 seconds
[2023-04-07T13:02:43.911-0300] {processor.py:153} INFO - Started process (PID=3635) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:02:43.916-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:02:43.917-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:02:43.917-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:02:43.922-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:02:43.920-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:02:43.922-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:02:43.951-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.043 seconds
[2023-04-07T13:03:34.273-0300] {processor.py:153} INFO - Started process (PID=3681) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:03:34.275-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:03:34.276-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:03:34.276-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:03:34.280-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:03:34.279-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:03:34.281-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:03:34.306-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.038 seconds
[2023-04-07T13:04:26.098-0300] {processor.py:153} INFO - Started process (PID=3727) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:04:26.103-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:04:26.105-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:04:26.104-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:04:26.109-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:04:26.108-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:04:26.110-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:04:26.140-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.046 seconds
[2023-04-07T13:05:20.028-0300] {processor.py:153} INFO - Started process (PID=3772) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:05:20.033-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:05:20.035-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:05:20.034-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:05:20.041-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:05:20.039-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:05:20.042-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:05:20.075-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.054 seconds
[2023-04-07T13:06:02.546-0300] {processor.py:153} INFO - Started process (PID=3808) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:06:02.548-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:06:02.549-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:06:02.549-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:06:02.553-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:06:02.552-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:06:02.554-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:06:02.581-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.040 seconds
[2023-04-07T13:06:43.729-0300] {processor.py:153} INFO - Started process (PID=3842) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:06:43.734-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:06:43.735-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:06:43.735-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:06:43.739-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:06:43.738-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:06:43.740-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:06:43.764-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.039 seconds
[2023-04-07T13:07:24.751-0300] {processor.py:153} INFO - Started process (PID=3877) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:07:24.754-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:07:24.756-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:07:24.756-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:07:24.760-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:07:24.759-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:07:24.761-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:07:24.788-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.042 seconds
[2023-04-07T13:08:04.429-0300] {processor.py:153} INFO - Started process (PID=3910) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:08:04.431-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:08:04.433-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:08:04.432-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:08:04.438-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:08:04.436-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:08:04.438-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:08:04.467-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.046 seconds
[2023-04-07T13:08:44.705-0300] {processor.py:153} INFO - Started process (PID=3946) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:08:44.708-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:08:44.709-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:08:44.709-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:08:44.713-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:08:44.711-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:08:44.713-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:08:44.739-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.038 seconds
[2023-04-07T13:09:27.481-0300] {processor.py:153} INFO - Started process (PID=3988) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:09:27.485-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:09:27.486-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:09:27.486-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:09:27.488-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:09:27.487-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:09:27.488-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:09:27.505-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.026 seconds
[2023-04-07T13:10:17.715-0300] {processor.py:153} INFO - Started process (PID=4034) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:10:17.717-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:10:17.719-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:10:17.718-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:10:17.723-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:10:17.722-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:10:17.723-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:10:17.750-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.040 seconds
[2023-04-07T13:10:58.753-0300] {processor.py:153} INFO - Started process (PID=4068) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:10:58.755-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:10:58.756-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:10:58.756-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:10:58.760-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:10:58.759-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:10:58.761-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:10:58.785-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.037 seconds
[2023-04-07T13:11:42.292-0300] {processor.py:153} INFO - Started process (PID=4104) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:11:42.297-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:11:42.298-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:11:42.298-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:11:42.302-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:11:42.301-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:11:42.303-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:11:42.330-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.042 seconds
[2023-04-07T13:12:25.480-0300] {processor.py:153} INFO - Started process (PID=4140) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:12:25.482-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:12:25.484-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:12:25.483-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:12:25.488-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:12:25.486-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:12:25.488-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:12:25.514-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.038 seconds
[2023-04-07T13:13:18.379-0300] {processor.py:153} INFO - Started process (PID=4186) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:13:18.384-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:13:18.386-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:13:18.385-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:13:18.390-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:13:18.389-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:13:18.391-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:13:18.416-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.042 seconds
[2023-04-07T13:14:04.712-0300] {processor.py:153} INFO - Started process (PID=4229) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:14:04.718-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:14:04.719-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:14:04.719-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:14:04.723-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:14:04.722-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:14:04.723-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:14:04.750-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.042 seconds
[2023-04-07T13:14:45.876-0300] {processor.py:153} INFO - Started process (PID=4263) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:14:45.878-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:14:45.879-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:14:45.879-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:14:45.885-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:14:45.884-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:14:45.885-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:14:45.912-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.041 seconds
[2023-04-07T13:15:27.108-0300] {processor.py:153} INFO - Started process (PID=4298) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:15:27.114-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:15:27.115-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:15:27.115-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:15:27.119-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:15:27.118-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:15:27.119-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:15:27.146-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.042 seconds
[2023-04-07T13:16:05.888-0300] {processor.py:153} INFO - Started process (PID=4332) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:16:05.893-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:16:05.894-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:16:05.894-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:16:05.898-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:16:05.897-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:16:05.899-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:16:05.924-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.041 seconds
[2023-04-07T13:17:01.649-0300] {processor.py:153} INFO - Started process (PID=4380) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:17:01.656-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:17:01.657-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:17:01.657-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:17:01.663-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:17:01.661-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:17:01.663-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:17:01.702-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.061 seconds
[2023-04-07T13:17:41.609-0300] {processor.py:153} INFO - Started process (PID=4414) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:17:41.611-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:17:41.612-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:17:41.612-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:17:41.616-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:17:41.615-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:17:41.617-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:17:41.644-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.040 seconds
[2023-04-07T13:18:22.598-0300] {processor.py:153} INFO - Started process (PID=4448) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:18:22.605-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:18:22.606-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:18:22.605-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:18:22.610-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:18:22.609-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:18:22.610-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:18:22.637-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.043 seconds
[2023-04-07T13:19:03.066-0300] {processor.py:153} INFO - Started process (PID=4483) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:19:03.068-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:19:03.070-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:19:03.069-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:19:03.074-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:19:03.072-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:19:03.074-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:19:03.099-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.037 seconds
[2023-04-07T13:19:51.411-0300] {processor.py:153} INFO - Started process (PID=4540) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:19:51.414-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:19:51.415-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:19:51.414-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:19:51.417-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:19:51.416-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:19:51.418-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:19:51.436-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.027 seconds
[2023-04-07T13:20:35.559-0300] {processor.py:153} INFO - Started process (PID=4602) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:20:35.561-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:20:35.562-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:20:35.562-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:20:35.564-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:20:35.564-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:20:35.565-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:20:35.579-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.021 seconds
[2023-04-07T13:21:13.633-0300] {processor.py:153} INFO - Started process (PID=4640) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:21:13.635-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:21:13.635-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:21:13.635-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:21:13.638-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:21:13.637-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:21:13.638-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:21:13.653-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.022 seconds
[2023-04-07T13:21:52.888-0300] {processor.py:153} INFO - Started process (PID=4678) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:21:52.892-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:21:52.893-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:21:52.892-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:21:52.895-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:21:52.894-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:21:52.895-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:21:52.910-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.025 seconds
[2023-04-07T13:22:39.114-0300] {processor.py:153} INFO - Started process (PID=4725) to work on /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:22:39.116-0300] {processor.py:743} INFO - Processing file /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2023-04-07T13:22:39.118-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:22:39.117-0300] {dagbag.py:532} INFO - Filling up the DagBag from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:22:39.122-0300] {logging_mixin.py:137} INFO - [2023-04-07T13:22:39.121-0300] {dagbag.py:341} ERROR - Failed to import: /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
Traceback (most recent call last):
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py", line 24, in <module>
    from pandas.tseries.holiday import USFederalHolidayCalendar
ModuleNotFoundError: No module named 'pandas'
[2023-04-07T13:22:39.123-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py
[2023-04-07T13:22:39.152-0300] {processor.py:175} INFO - Processing /home/rai/.local/lib/python3.10/site-packages/airflow/example_dags/plugins/workday.py took 0.043 seconds
